Feat/chart generator
hannansatopay/devstar pull request #20
Opened 2023-10-02 08:09 UTC by Abhieo07

#  Added Chart-generator feature
Thank you for giving me the opportunity to contribute in your project. I have added chart-generator feature into yours site which is done in svelte.kit as specified in the CONTRIBUTORS.md, However for the graphs/charts representation i have used Chart.js library.

There is a prototype video link:  
       https://drive.google.com/file/d/1de4tzFEMkDM2EeklFONeQFZoNl8Q59MZ/view?usp=drive_link

##  User Experience

-    In this module a client/user can upload a file (format excepted is .csv, .json).
-    Then it can choose what kind of graph/chart they want to generate like bar,line,pie,etc. 
-    As the file can have multiple dimension and so the user will have leverage to choose x,y axes to plot the graphs.
-    Once the user click on generate button it will automatically as per users specified axes and the chart type.
-    If the user want to download that particular graph it can download by clicking on the download button.
-    The download format will be of png.

###  By default Graph
  - Once the user enter the site there's a random graph generated, This is intentionally done so that the user can Visualize the system at once, User can check all the functionality like plotting different types of charts(bar,pie,etc), user can understand the system easily.

### Snapshots

![Screenshot (86)](https://github.com/hannansatopay/devstar/assets/95901992/025191fa-7d2e-45ba-8940-d746fae893d9)
![Screenshot (87)](https://github.com/hannansatopay/devstar/assets/95901992/c8b5f7ef-0298-499a-90af-39550f1a267b)

### File Used in the video
[data.csv](https://github.com/hannansatopay/devstar/files/12780733/data.csv)

### Downloaded file
![chart](https://github.com/hannansatopay/devstar/assets/95901992/cef954c4-1c83-41ca-bddc-0c91aef312e6)

**Note: No data is stored in server.**

2023-10-02 08:14 UTC, Abhieo07 commented
1st commit was for adding the new feature and the 2nd commit was for adding the new icons into `\devstar\static\fonts\icomoon.svg` due to which i had to alter `\devstar\static\fonts`.
 Once again thank you for this wonderful opportunity hoping for positive response.

2023-10-10 09:20 UTC, hannansatopay requested changes
@Abhieo07 This is good! We need to work on few more changes before we can merge this to the original repo. Let's discuss.

2023-10-12 07:56 UTC, Abhieo07 commented
Yea sure!

On Tue, Oct 10, 2023, 2:50 PM Hannan Satopay ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @Abhieo07 <https://github.com/Abhieo07> This is good! We need to work on
> few more changes before we can merge this to the original repo. Let's
> discuss.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hannansatopay/devstar/pull/20#pullrequestreview-1667007506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW3VSKECQS3OTRRICVZZUO3X6UHNDAVCNFSM6AAAAAA5PBKUFOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRXGAYDONJQGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-20 09:01 UTC, hannansatopay approved these changes

2023-10-20 09:01 UTC, merged